; Icons from Font Awesome Free 6.4.0 Solid (see LICENSE-FontAwesome.txt):
; each size only with the icons drawn at it (fa-<size>)

; Status bar: wifi
[fa-10]
size  = 10
chars = 0xF1EB

; Status bar: battery; settings: chevron-right; system: microchip, memory, hard-drive
[fa-12]
size  = 12
chars = 0xF241,0xF054,0xF2DB,0xF538,0xF0A0

; Back buttons: chevron-left; settings: wifi, display, circle-info; store: calculator, message
[fa-16]
size  = 16
chars = 0xF053,0xF1EB,0xE163,0xF05A,0xF1EC,0xF27A

; Music: backward-step, forward-step
[fa-18]
size  = 18
chars = 0xF048,0xF051

; Home screen tiles: gear, microchip, music, house-signal, shop; music: play, pause
[fa-20]
size  = 20
chars = 0xF013,0xF2DB,0xF001,0xE012,0xF54F,0xF04B,0xF04C

; Weather panel: cloud-sun; smart home: lightbulb, temperature-half, lock
[fa-24]
size  = 24
chars = 0xF6C4,0xF0EB,0xF2C9,0xF023

; Store banner: gamepad
[fa-48]
size  = 48
chars = 0xF11B

; Music: compact-disc
[fa-60]
size  = 60
chars = 0xF51F

; Weather: cloud-sun
[fa-72]
size  = 72
chars = 0xF6C4
