; Inter Bold (font-bold)
chars = 0x20-0x7E,0xB0,0xD3,0xF3,0x104-0x107,0x118-0x119,0x141-0x144,0x15A-0x15B,0x179-0x17C,0x2022

[inter-b-9]
size = 9

[inter-b-12]
size = 12

[inter-b-14]
size = 14

[inter-b-18]
size = 18

; The home screen's clock - text-5xl, tracking-tighter (-0.05em)
[inter-b-48-clock]
size     = 48
chars    = 0x30-0x3A
tracking = -2.4

; The weather's temperature - text-6xl, tracking-tighter
[inter-b-60-temp]
size     = 60
chars    = 0x2D,0x30-0x39,0x43,0xB0
tracking = -3
